project:
  type: website
  output-dir: docs

website:
  title: "Tidy Mixed Models in R"
  navbar:
    left:
      - href: code/tidymixedmodels.qmd
        text: 'AGSA Workshop - Fall 2022'
    right: 
      - icon: globe
        href: https://adriancorrendo.github.io/
      - icon: github
        href: https://github.com/adriancorrendo/tidymixedmodelsweb/
      - icon: twitter
        href: https://twitter.com/aacorrendo
      - icon: linkedin
        href: https://www.linkedin.com/in/adriancorrendo/
    
format:
  html:
    theme: unite
    highlight-style: pygments
    css: styles.css
    toc: true
    toc-title: "Content"
    toc-location: right
    code-tools: 
      source: true
      toggle: false
      copy: true
      link: true
    
freeze: auto

editor: visual

